### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [aliemen/Visualization-of-the-Fourier-series#1]
I see you have no LICENSE file for this project.  The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by aliemen** [comment]
Hi, wow as someone who doesn't use GitHub very often, I somehow didn't realize that people had written something here about my code. Thanks for bringing it to my attention though, I should and will look into that!
