### ISSUE TITLE
Code comments in FourierMain.py are truncated

### ISSUE THREAD

**Issue by JoonasD6** [aliemen/Visualization-of-the-Fourier-series#2]
in FourierMain.py, the comment for line 97 says "number of fourier coefficients, will calculate from k=-N up to k=N, the more " and it looks like there was supposed to be a further explanation what happens when you increaset he value.

![image](https://user-images.githubusercontent.com/2440687/147235754-4d7cdf4e-96ac-49e3-89b4-5274e39705c1.png)

(It's "quite obvious" what it does, but this is a documentation report.)

**Comment by aliemen** [comment]
Hi, sorry that I never replied to your comments. Since I don't really use GitHub much I somehow never noticed them... But you are right! Even if a little late, I will for the sake of completeness update my comments in the code
